### ISSUE TITLE
[Bug] Error watching stream + Web socket error

### ISSUE THREAD

**Issue by Oplikk** [TychoTheTaco/Twitch-Drops-Bot#111]
**Describe the bug**
Multiple "Error watching stream" like in #73 

Web socket frame error  - sometimes appears, no idea

Running on Pi Zero 2, raspbian OS, npm, node up to date, using default chromium browser
 (sudo apt-get install chromium-browser --yes)

Steps taken: Increased load_timeout_secs , failed_stream_timeout.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://imgur.com/a/ftJSCaA)

**Logs**
-Attachment
[log-1652880230637.txt](https://github.com/TychoTheTaco/Twitch-Drops-Bot/files/8716646/log-1652880230637.txt)

**Comment by TychoTheTaco** [comment]
I see this error in the logs, which means you are probably using NodeJS version <16, this bot requires at least v16.
```
[2022-05-18 14:24:03] [debug] TypeError: numbersA.at is not a function
    at compareVersionString (file:///home/Oplik/Bot/dist/utils.js:58:40)
    at file:///home/Oplik/Bot/dist/index.js:71:17
    at Generator.next (<anonymous>)
    at fulfilled (file:///home/Oplik/Bot/dist/index.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I also see a few of these, which indicate that the page is not loading fast enough, so that is most likely a network issue. Could also be that your Pi is too slow or low on RAM.
```
[2022-05-18 14:25:32] [debug] TimeoutError: Navigation timeout of 60000 ms exceeded
    at /home/Oplik/Bot/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:108:111
```

**Comment by Oplikk** [comment]
Turns out i had two instalations of Node on my Pi, which caused some collisions. Fixed
