### ISSUE TITLE
[Bug] View streams when no drop campaigns are active

### ISSUE THREAD

**Issue by xCorteX** [TychoTheTaco/Twitch-Drops-Bot#121]
**Describe the bug**
since the new update it doesn't work anymore
"View streams when no drop campaigns are active"

with the previous version it works perfectly

**Screenshots**
1.1.0
![1 1 0](https://user-images.githubusercontent.com/37551164/172496945-a200f762-1e04-4fd1-a02e-216a00bd4e5a.png)

1.2.0
![1 2 0](https://user-images.githubusercontent.com/37551164/172496969-c83787e8-2901-4283-85fd-0d9f7e36f743.png)

**Logs**
[2022-06-08 00:19:11] [info] Found 30 good streams
[2022-06-08 00:19:12] [warn] This stream has no available Drops. This is likely because you already completed this campaign
[2022-06-08 00:19:12] [info] No drop campaigns active, watching a stream instead.
[2022-06-08 00:19:12] [error] Error getting next idle stream!
[2022-06-08 00:19:12] [debug] TypeError: Cannot read properties of undefined (reading 'login')
    at getStreamUrl (file:///C:/Users/XXX/Desktop/twitch%20bot%201.2.0/dist/twitch.js:358:58)
    at TwitchDropsBot.<anonymous> (file:///C:/Users/XXX/Desktop/twitch%20bot%201.2.0/dist/twitch_drops_bot.js:771:35)
    at Generator.next (<anonymous>)
    at fulfilled (file:///C:/Users/XXX/Desktop/twitch%20bot%201.2.0/dist/twitch_drops_bot.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2022-06-08 00:19:12] [info] No idle streams available! sleeping for a bit...
[2022-06-08 00:19:12] [debug] waiting for waitNotify: 4598

**Comment by TychoTheTaco** [comment]
Fixed in the latest release.
