### ISSUE TITLE
[Bug] Uncaught exception: TimeoutError

### ISSUE THREAD

**Issue by jaredkotoff** [TychoTheTaco/Twitch-Drops-Bot#155]
There may not be enough information here, but noticed this error while watching logs
```
[info] Watching stream: https://www.twitch.tv/beast1k
[error] Uncaught exception: TimeoutError: Timeout exceeded while waiting for event
    at listOnTimeout (node:internal/timers:564:17)
    at Timeout.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/util.js:167:28)
    at process.processTimers (node:internal/timers:507:7)
(node:1) UnhandledPromiseRejectionWarning: TimeoutError: Timeout exceeded while waiting for event
    at Timeout.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/util.js:167:28)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[error] Error watching stream
[info] Watched stream for 0 minutes
```

**Comment by tired9494** [comment]
```
[2022-10-08 16:41:04] [warn] Overriding browser option because we are inside a docker container!
[2022-10-08 16:41:04] [warn] Adding browser option: --no-sandbox because we are inside a docker container!
[2022-10-08 16:41:05] [warn] No username specified! Using existing cookies: cookies-username.json
[2022-10-08 16:41:05] [info] Restoring cookies from last session.
[2022-10-08 16:41:34] [info] Processing campaign: Overwatch 2 Overwatch 2 Kiriko Sukajan Skin Campaign
[2022-10-08 16:41:35] [info] Found 30 good streams
[2022-10-08 16:41:35] [info] Watching stream: https://www.twitch.tv/fextralife
[2022-10-08 16:42:05] [error] Error watching stream
[2022-10-08 16:42:05] [info] [36mWatched stream for 0 minutes[39m
[2022-10-08 16:42:06] [info] Found 30 good streams
[2022-10-08 16:42:06] [info] Watching stream: https://www.twitch.tv/fextralife
[2022-10-08 16:42:36] [error] Uncaught exception: TimeoutError: Timeout exceeded while waiting for event
    at Timeout.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/util.js:168:28)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[2022-10-08 16:42:41] [error] Error watching stream
[2022-10-08 16:42:41] [info] [36mWatched stream for 0 minutes[39m
[2022-10-08 16:42:42] [info] Found 30 good streams
[2022-10-08 16:42:42] [info] Watching stream: https://www.twitch.tv/fextralife
```
I'm getting the same error

**Comment by tired9494** [comment]
ah just had to increase the timeout
