### ISSUE TITLE
Crashing after Stream went down

### ISSUE THREAD

**Issue by yukaiin** [TychoTheTaco/Twitch-Drops-Bot#183]
So when the stream ends it just crashes.

These are my logs:
[2022-08-20 00:53:04] [debug] latest release version: v1.2.5
[2022-08-20 00:53:04] [debug] Done checking for updates
[2022-08-20 00:53:57] [debug] Updating drop campaigns...
[2022-08-20 00:53:57] [debug] Found 106 campaigns.
[2022-08-20 00:54:29] [debug] Found 2 pending campaigns.
[2022-08-20 00:56:01] [debug] PONG
[2022-08-20 00:57:39] [debug] url mismatch: https://www.twitch.tv/kenji?referrer=raid vs https://www.twitch.tv/shylily
[2022-08-20 00:57:39] [info] Stream went down
[2022-08-20 00:57:39] [info] [36mWatched stream for 413 minutes[39m
[2022-08-20 00:57:40] [error] Error: net::ERR_ABORTED at about:blank
    at navigate (/home/pi/Desktop/yukain/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:200:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (/home/pi/Desktop/yukain/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:174:21)
    at async Frame.goto (/home/pi/Desktop/yukain/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:616:16)
    at async Page.goto (/home/pi/Desktop/yukain/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1092:16)

**Comment by TychoTheTaco** [comment]
This looks like a duplicate of #129, which I still haven't been able to fix yet.

**Comment by yukaiin** [comment]
I think it is. Could be because the bot thinks it is on about:blank while actually still watching the hosted stream. That's what i think is happening there.
