### ISSUE TITLE
[Bug] Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by JourneyOver** [TychoTheTaco/Twitch-Drops-Bot#188]
**Describe the bug**
Docker image (:latest) failing to fully start due to the error with the browser failing to launch and creating a bunch of log files due to it failing (I didn't notice it failing till I had almost 1000 log files). If I pull an older image (:v1.2.5) or even an older SHA256 (@sha256:eb0f7645d3a11c64b8f6506a508ede7881964ec8d397abb5393fc801e99e8ff5) everything works as expected.

**Logs**
```
[2022-09-03 16:35:11] [warn] Overriding browser option because we are inside a docker container!
[2022-09-03 16:35:11] [warn] Overriding headless_login option because we are inside a docker container!
[2022-09-03 16:35:11] [warn] Adding browser option: --no-sandbox because we are inside a docker container!
[2022-09-03 16:35:11] [error] Error: Failed to launch the browser process!
Error: Can't open display: 


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

The log with the error message, it would recreate another log with the same error message again over and over again every few seconds or so until the docker container is stopped.

**Comment by TychoTheTaco** [comment]
I'm not able to reproduce this. What does your config look like? Are you trying to use `headless: false` with docker? I'm pretty sure that won't work and seems like it could cause that error; although when I try `headless: false` I get a different error so I'm not so sure about that.

**Comment by JourneyOver** [comment]
This is my config:

```
{
  "browser": "google-chrome",
  "games": [
    "29307",
    "490100",
    "506416",
    "417969",
    "19357",
    "497057",
    "493597",
    "511230"
  ],
  "headless": true,
  "headless_login": true,
  "interval": 15,
  "load_timeout_secs": 30,
  "failed_stream_retry": 3,
  "failed_stream_timeout": 30,
  "browser_args": [],
  "watch_unlisted_games": false,
  "hide_video": true,
  "show_account_not_linked_warning": true,
  "ignored_games": [],
  "attempt_impossible_campaigns": true,
  "watch_streams_when_no_drop_campaigns_active": true,
  "do_version_check": false,
  "broadcasters": [
    "markiplier",
    "jacksepticeye",
    "minion777",
    "joshstrifehayes",
    "kitboga",
    "jessecox",
    "linustech",
    "bajheera",
    "preachlfw",
    "dexbonus",
    "captainsparklez",
    "tectone",
    "illythekitty",
    "coppersantv"
  ],
  "tui": {
    "enabled": false
  },
  "updates": {
    "type": "dev",
    "enabled": false
  },
  "logging": {
    "enabled": true,
    "level": "info"
  },
  "notifications": {
    "discord": []
  }
}
```

and no I never turned headless mode to false as I felt it would be kind of pointless to have it turned to false when running in docker. I originally had the games be the names of the games instead of the ID like above, but that was when I was running with `:latest` and well since I'm running `:latest-release` atm I had to switch it back to IDs.

I'll try running `:latest` again and see if it's still an issue or not.

**Comment by JourneyOver** [comment]
so an edit onto my last one:

it's still running into the same error on `:latest` and creating a log file each time it throws the error

```
[2022-09-09 23:13:23] [warn] Overriding browser option because we are inside a docker container!
[2022-09-09 23:13:23] [warn] Adding browser option: --no-sandbox because we are inside a docker container!
[2022-09-09 23:13:23] [error] Error: Failed to launch the browser process!
Error: Can't open display: 


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by JourneyOver** [comment]
and with logging set to `debug` instead of `info` which honestly doesn't give a whole lot more information..

```
[2022-09-09 23:17:35] [debug] current system time: Fri Sep 09 2022 23:17:35 GMT-0500 (Central Daylight Time)
[2022-09-09 23:17:35] [debug] git commit hash: 3ef8770e260f2a6b7268061eb17c448df39a4997
[2022-09-09 23:17:35] [debug] NodeJS version: v18.8.0
[2022-09-09 23:17:35] [warn] Overriding browser option because we are inside a docker container!
[2022-09-09 23:17:35] [warn] Adding browser option: --no-sandbox because we are inside a docker container!
[2022-09-09 23:17:35] [debug] Using config: {
    "browser": "chromium",
    "games": [
        "29307",
        "490100",
        "506416",
        "417969",
        "19357",
        "497057",
        "493597",
        "511230"
    ],
    "headless": true,
    "headless_login": true,
    "interval": 15,
    "load_timeout_secs": 30,
    "failed_stream_retry": 3,
    "failed_stream_timeout": 30,
    "browser_args": [
        "--mute-audio",
        "--disable-background-timer-throttling",
        "--disable-backgrounding-occluded-windows",
        "--disable-renderer-backgrounding",
        "--window-size=1920,1080",
        "--disable-features=HardwareMediaKeyHandling",
        "--no-sandbox"
    ],
    "watch_unlisted_games": false,
    "hide_video": true,
    "show_account_not_linked_warning": true,
    "ignored_games": [],
    "attempt_impossible_campaigns": true,
    "watch_streams_when_no_drop_campaigns_active": true,
    "do_version_check": false,
    "broadcasters": [
        "markiplier",
        "jacksepticeye",
        "minion777",
        "joshstrifehayes",
        "kitboga",
        "jessecox",
        "linustech",
        "bajheera",
        "preachlfw",
        "dexbonus",
        "captainsparklez",
        "tectone",
        "illythekitty",
        "coppersantv"
    ],
    "tui": {
        "enabled": false
    },
    "updates": {
        "type": "dev",
        "enabled": false
    },
    "logging": {
        "enabled": true,
        "level": "debug"
    },
    "notifications": {
        "discord": []
    }
}
[2022-09-09 23:17:35] [error] Error: Failed to launch the browser process!
Error: Can't open display: 


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:289:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:277:24)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by JourneyOver** [comment]
Seems that whatever was going on is now fixed in `:latest` so I am going to go ahead and close this issue.
