### ISSUE TITLE
[Bug] Failed to read config file EACCES

### ISSUE THREAD

**Issue by Textic** [TychoTheTaco/Twitch-Drops-Bot#199]
[opc@instance-20220916-1615 Twitch-Drops-Bot]$ sudo docker run --rm -v ${PWD}:/app/data -i -t --sig-proxy=false ghcr.io/
tychothetaco/twitch-drops-bot:latest-release
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[2022-09-17 00:08:46] [info] Loading config file: config.json
[2022-09-17 00:08:46] [error] Failed to read config file!
[2022-09-17 00:08:46] [error] Error: EACCES: permission denied, open 'config.json'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at ConfigurationParser.parse (file:///app/dist/configuration_parser.js:57:40)
    at file:///app/dist/index.js:345:42
    at Generator.next (<anonymous>)
    at file:///app/dist/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///app/dist/index.js:3:12)
    at main (file:///app/dist/index.js:342:12)
    at file:///app/dist/index.js:588:5

**Comment by Textic** [comment]
fixed, i changed podman to docker
