### ISSUE TITLE
ERROR: Error: No node found for selector: [data-a-target="player-settings-menu-item-quality"]

### ISSUE THREAD

**Issue by agret** [TychoTheTaco/Twitch-Drops-Bot#2]
Watching stream: https://www.twitch.tv/frtin
Setting stream quality to lowest available...
ERROR: Error: No node found for selector: [data-a-target="player-settings-menu-item-quality"]
    at Object.assert (M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at DOMWorld.click (M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:277:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async setLowestStreamQuality (M:\Development\Twitch-Drops-Bot\index.js:263:5)
    at async watchStreamUntilDropCompleted (M:\Development\Twitch-Drops-Bot\index.js:202:5)
    at async processCampaign (M:\Development\Twitch-Drops-Bot\index.js:364:17)
    at async M:\Development\Twitch-Drops-Bot\index.js:616:17
Stream failed too many times. Giving up...

**Comment by agret** [comment]
Processing campaign: Trove Trove LP 2021 Drops 2
Drop: Dev Dream
Found 10 active streams
Watching stream: https://www.twitch.tv/frtin
Watching stream |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% | 0 / 240 minutes | Remaining: 240 minutes
No progress was made since last update!
Found 9 active streams
Watching stream: https://www.twitch.tv/frtin
Watching stream |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% | 0 / 240 minutes | Remaining: 240 minutes
No progress was made since last update!
Found 9 active streams
Watching stream: https://www.twitch.tv/frtin
Watching stream |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% | 0 / 240 minutes | Remaining: 240 minutes

**Comment by agret** [comment]
Processing campaign: SMITE Smite 8.7 Week 5
Drop: Viewer Points
Found 30 active streams
Watching stream: https://www.twitch.tv/smitegame
Watching stream |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% | 0 / 240 minutes | Remaining: 240 minutes
No progress was made since last update!
Found 30 active streams
Watching stream: https://www.twitch.tv/smitegame
Watching stream |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% | 0 / 240 minutes | Remaining: 240 minutes
No progress was made since last update!
Found 30 active streams
Watching stream: https://www.twitch.tv/smitegame
Watching stream |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% | 0 / 240 minutes | Remaining: 240 minutes

**Comment by TychoTheTaco** [comment]
It seems like you might be using the default browser that comes with puppeteer which doesn't work. Try using a standalone installation of Chrome.

**Comment by Kraker01** [comment]
I'm experiencing the same problem. My config file is the following: 
`{
	"browser":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
	"games":[]
}
`

The error I receive is the following one: 
`Setting stream quality to lowest available...
ERROR: Error: No node found for selector: [data-a-target="player-settings-menu-item-quality"]
    at Object.assert (C:\Twitch-Drops-Bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at DOMWorld.click (C:\Twitch-Drops-Bot-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:277:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async setLowestStreamQuality (C:\Twitch-Drops-Bot-master\index.js:274:5)
    at async watchStreamUntilDropCompleted (C:\Twitch-Drops-Bot-master\index.js:213:5)
    at async processCampaign (C:\Twitch-Drops-Bot-master\index.js:375:17)
    at async C:\Twitch-Drops-Bot-master\index.js:650:17
Stream failed too many times. Giving up...`

**Comment by TychoTheTaco** [comment]
I just pushed a potential fix.

**Comment by Kraker01** [comment]
Seems like it's working like a charm.

Found 9 active streams
Watching stream: https://www.twitch.tv/ftlak
Watching stream |█████████████████████████░░░░░░░░░░░░░░░| 63% | 57 / 90 minutes | Remaining: 33 minutes

**Comment by TychoTheTaco** [comment]
Can you try using branch `bug-2`? It will create some files: `page_content_0.html`, `settings_menu_0.html`, etc. that will help me debug. You can attach the files here.

Also, you can try with the `--headful` option and see if anything unexpected happens (see if the settings menu actually opens).

**Comment by agret** [comment]
Switched to the bug-2 branch and I can confirm the updated function with more waits has solved the issue for me.

**Comment by Kraker01** [comment]
Switched to branch bug-2 

It's working. Sorry for late response.

**Comment by TychoTheTaco** [comment]
Can you attach all the `page_content_*.html` and `settings_menu_*.html` here (drag and drop them instead of copy paste).

**Comment by TychoTheTaco** [comment]
I think I've figured out what's happening based on the contents you posted. The script fails to click the "accept mature content" button and so the settings button never becomes available. I've changed it now so that it waits longer for the page to load completely which should hopefully fix the issue.

**Comment by Kraker01** [comment]
Downloaded and set up from scratch. I think there's a new error popping up, I'll attach all the needed files.

![screenshot](https://user-images.githubusercontent.com/20519780/130583452-a7121660-5e82-48f4-b9b9-5dc2615876cd.png)
[page_content_0.zip](https://github.com/TychoTheTaco/Twitch-Drops-Bot/files/7037682/page_content_0.zip)

**Comment by agret** [comment]
Sadly still broken, i'm using the latest commit from 8hrs ago on the main branch and just got this again

`Watching stream |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0 / 60 minutesFailed to set stream to lowest quality!
TimeoutError: waiting for selector `[data-a-target="player-settings-menu-item-quality"]` failed: timeout 30000ms exceeded
    at new WaitTask (M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOM
World.js:420:26)
No progress was made since last update!M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Que
Found 1 active streams
Watching stream: https://www.twitch.tv/nimbleneurontch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.
Watching stream |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0 / 60 minutesFailed to set stream to lowest quality!
TimeoutError: waiting for selector `[data-a-target="player-settings-menu-item-quality"]` failed: timeout 30000ms exceededr
    at new WaitTask (M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOM
World.js:420:26)
    at Object.internalHandler.waitFor (M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Que
ryHandler.js:31:77)s (<anonymous>)
    at DOMWorld.waitForSelector (M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.
js:313:29)
    at Frame.waitForSelector (M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager
.js:841:51)
    at Page.waitForSelector (M:\Development\Twitch-Drops-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1335:
33)
    at setLowestStreamQuality (M:\Development\Twitch-Drops-Bot\index.js:295:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

**Comment by agret** [comment]
Now back onto the bug2 branch and here's my error

`Processing campaign: Eternal Return EMOTE DROPS! - 소니쇼 팀
Drop: Emote - 소니쇼
Found 1 active streams
Watching stream: https://www.twitch.tv/sonycast_
SFailed to set stream to lowest quality!
TypeError: Cannot read property 'getProperty' of undefined
    at setLowestStreamQuality (M:\Development\Twitch-Drops-Bot-Bug\index.js:304:132)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
saved screenshot`

[page_content.zip](https://github.com/TychoTheTaco/Twitch-Drops-Bot/files/7038923/page_content.zip)

**Comment by Kyraminol** [comment]
I should have fixed this issue with pull request https://github.com/TychoTheTaco/Twitch-Drops-Bot/pull/3

**Comment by TychoTheTaco** [comment]
This issue should be fixed now. The popup was blocking puppeteer from clicking. I've changed it so that the clicks are now done directly via JavaScript instead of through puppeteer, which means elements that are under other elements can still be clicked.

One thing I noticed while testing is that this error still happens if the stream fails to load, but this seemed to only happen on the first attempt after starting the script.

**Comment by Kraker01** [comment]
tested latest master branch 

working like a charm
