### ISSUE TITLE
Stops working if internet connection drops out

### ISSUE THREAD

**Issue by agret** [TychoTheTaco/Twitch-Drops-Bot#20]
The bot stops working if the internet drops, it just gets stuck in a sleep loop without ever retrying.

```
[2021-11-23 19:51:45] [info] 51) Project Genesis Project Genesis Loot
Watching https://www.twitch.tv/wakeupamadeus | Viewers: 79 | Uptime: 6:19:04
Bounty Coins ███░░░░░░░░░░░░░░░░░ 30 / 240 minutes
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: New World The Royal Fisher
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Crowfall Crowfall Nov 20 - 23
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Don't Starve Together Don't Starve Together - Shellbound Deck Illuminator
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return ER Partners DROPS! - 네브짱
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return ER Partners DROPS! - 시간에이
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return PRO_fessors DROPS!
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return ER Partners DROPS! - ECYoon
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return ER Partners DROPS! - YukiUsada
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return ER Partners DROPS! - 후참
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return ER Partners DROPS! - 농약엑기스
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return ER Partners DROPS! - 스키퍼
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return Eternal Return Challengers:APAC South DROPS!
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return ER Partners DROPS! - 꾸미오
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Eternal Return ER Partners DROPS! - lNeroTV
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Trove Trove Friendsgiving 2021
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: ELYON NA/EU - Twitch Drops for Partners
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: ELYON NA/EU - Twitch Drops for Partners - Daily (Nov. 23)
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Black Desert Online November Day 13 (11/22)
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Paladins Paladins Drops 21.7 Wk2
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Knockout City Official KO City S3W7
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: SMITE SMITE 8.11 Week 1
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Knockout City KO City Season 3, Week 7
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Apex Legends Apex Escape Community Created Drop 1
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Overwatch Overwatch - Cassidy's New Blood Challenge
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Madden NFL 22 Good Morning Madden
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: World of Warships Update 0.10.10: Part 1
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: World of Tanks Weekly Watchers November
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Black Desert Online November Twitch Drops
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Burke Black - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Quill18 - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Frankie Ward - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Saddummy - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Lewis - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND HandOfBlood - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Marbozir - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Andrew Channel - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Lomadiah - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND BRKsEDU - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND 2DKiri - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND CohhCarnage - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Joueur du Grenier - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND GamerZakh - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Tian Chi - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND ZeratoR - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Alexey Khaletski - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND Shurjoka - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: HUMANKIND The Spiffing Brit - Humankind
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Goose Goose Duck GGD 11/04 - 12/02/2021
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: World of Warships Official Channel Weekly Drop
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Goose Goose Duck Goose Goose Duck - Dhalucard
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Processing campaign: Project Genesis Project Genesis Loot
[2021-11-23 20:02:59] [error] getaddrinfo ENOTFOUND gql.twitch.tv Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
[2021-11-23 20:02:59] [info] Sleeping for 15 minutes...
[2021-11-23 20:06:45] [info] Updating drop campaigns...
(node:11568) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND gql.twitch.tv
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 57)
(node:11568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2021-11-23 20:17:59] [info] Sleeping for 15 minutes...
[2021-11-23 20:33:02] [info] Sleeping for 15 minutes...
[2021-11-23 20:48:02] [info] Sleeping for 15 minutes...
[2021-11-23 21:03:02] [info] Sleeping for 15 minutes...
[2021-11-23 21:18:02] [info] Sleeping for 15 minutes...
[2021-11-23 21:33:02] [info] Sleeping for 15 minutes...
[2021-11-23 21:48:02] [info] Sleeping for 15 minutes...
[2021-11-23 22:03:02] [info] Sleeping for 15 minutes...
[2021-11-23 22:18:02] [info] Sleeping for 15 minutes...
[2021-11-23 22:33:02] [info] Sleeping for 15 minutes...
[2021-11-23 22:48:02] [info] Sleeping for 15 minutes...
[2021-11-23 23:03:02] [info] Sleeping for 15 minutes...
[2021-11-23 23:18:02] [info] Sleeping for 15 minutes...
[2021-11-23 23:33:02] [info] Sleeping for 15 minutes...
[2021-11-23 23:48:02] [info] Sleeping for 15 minutes...
[2021-11-24 00:03:02] [info] Sleeping for 15 minutes...
[2021-11-24 00:18:02] [info] Sleeping for 15 minutes...
[2021-11-24 00:33:02] [info] Sleeping for 15 minutes...
[2021-11-24 00:48:02] [info] Sleeping for 15 minutes...
[2021-11-24 01:03:02] [info] Sleeping for 15 minutes...
[2021-11-24 01:18:02] [info] Sleeping for 15 minutes...
[2021-11-24 01:33:02] [info] Sleeping for 15 minutes...
[2021-11-24 01:48:02] [info] Sleeping for 15 minutes...
```

**Comment by TychoTheTaco** [comment]
Is this using the latest version of the repo? It should just retry until the connection comes back.

**Comment by TychoTheTaco** [comment]
Closing for inactivity.
