### ISSUE TITLE
[Bug] [error] Failed to claim drop 

### ISSUE THREAD

**Issue by space2lim** [TychoTheTaco/Twitch-Drops-Bot#202]
```
[2022-09-18 11:05:33] [error] Failed to claim drop reward
[2022-09-18 11:05:33] [debug] Error: API error: {
    "errors": [
        {
            "message": "failed integrity check"
        }
    ],
    "extensions": {
        "challenge": {
            "type": "integrity"
        },
        "durationMilliseconds": 1,
        "operationName": "DropsPage_ClaimDropRewards",
        "requestID": "01GD84CRY9G4BV1ZEQXQ0Z61NB"
    }
}
    at Client.<anonymous> (file:///app/dist/twitch.js:307:19)
    at Generator.next (<anonymous>)
    at fulfilled (file:///app/dist/twitch.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2022-09-18 11:05:33] [debug] {
    "id": "30ab3ab0-c323-4031-8eeb-95a2deee1037",
    "name": "Esports Pack 1",
    "startAt": "2022-09-12T15:00:00Z",
    "endAt": "2022-09-19T05:00:00Z",
    "preconditionDrops": null,
    "requiredMinutesWatched": 240,
    "benefitEdges": [
        {
            "benefit": {
                "id": "r6s_stage_3_2022_w1",
                "imageAssetURL": "https://static-cdn.jtvnw.net/twitch-drops-assets-prod/BENEFIT-377e7324-3d1c-4d31-8b6d-aefa870b5d1e.jpeg",
                "name": "Esports Pack Stage 3 W1",
                "__typename": "DropBenefit"
            },
            "entitlementLimit": 1,
            "claimCount": 0,
            "__typename": "DropBenefitEdge"
        }
    ],
    "self": {
        "hasPreconditionsMet": true,
        "currentMinutesWatched": 240,
        "isClaimed": false,
        "dropInstanceID": "430c81fe-81a2-4341-a5d8-3c04a79187f3",
        "__typename": "TimeBasedDropSelfEdge"
    },
    "campaign": {
        "id": "ab407d91-b2b1-4a33-8af3-ab4cce1829c5",
        "accountLinkURL": "https://drops-register.ubi.com/",
        "self": {
            "isAccountConnected": true,
            "__typename": "DropCampaignSelfEdge"
        },
        "__typename": "DropCampaign"
    },
    "__typename": "TimeBasedDrop"
}
```

**Comment by TychoTheTaco** [comment]
This is fixed in the latest release.

**Comment by space2lim** [comment]
Solved, thank you.
