### ISSUE TITLE
Stops working after all drops claimed

### ISSUE THREAD

**Issue by InstreakTV** [TychoTheTaco/Twitch-Drops-Bot#21]
When i collect all three drops in the campain (rocket league) it stops working sometimes. It still sets timeouts but wont find new campains/streams until i restart it.

Cannot read property 'getProperty' of null TypeError: Cannot read property 'getProperty' of null
    at StreamPage.getUptime (/home/pi/Desktop/Twitch-Drops-Bot-master/src/pages/stream.js:51:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async watchStreamUntilDropCompleted (/home/pi/Desktop/Twitch-Drops-Bot-master/src/index.js:206:108)
    at async processCampaign (/home/pi/Desktop/Twitch-Drops-Bot-master/src/index.js:379:17)
    at async /home/pi/Desktop/Twitch-Drops-Bot-master/src/index.js:817:17

This is the error code and after it it only shows this in an infinite loop (there is no stream it can watch)

Watching https://www.twitch.tv/rocketleagueapac | Viewers: 14260 | Uptime: 5:27:34
Fall Split Suite ░░░░░░░░░░░░░░░░░░░░ 0 / 120 minutes
[2021-11-23 17:13:37] [info] Sleeping for 15 minutes...
[2021-11-23 17:16:04] [info] Updating drop campaigns...
[2021-11-23 17:16:04] [info] Found 60 active campaigns.
[2021-11-23 17:16:04] [info] Found 0 pending campaigns.

Also so viewer/time wont change. It just repeats the message over and over

**Comment by TychoTheTaco** [comment]
Are you using the latest version of this repo? I'm unable to reproduce the error.

**Comment by InstreakTV** [comment]
Nope. Im testing right now but there are no campains. I write if it happens again

**Comment by InstreakTV** [comment]
Works fine now. Still very bad performance with the pi it times out a lot. But i think thats a problem with the pi not ur bot.

**Comment by TychoTheTaco** [comment]
There was a `load_timeout_secs` option added recently, maybe increasing that can help?

**Comment by InstreakTV** [comment]
I dont know if im doing something wrong but changing the config doesnt work for me.

**Comment by TychoTheTaco** [comment]
That's strange. Are you sure you are changing the correct file? You can also provided it as a command-line argument instead: `--load-timeout-secs 60`.

**Comment by InstreakTV** [comment]
Also fixed now
