### ISSUE TITLE
[Bug] Bot unable to claim drops or points

### ISSUE THREAD

**Issue by mincheri** [TychoTheTaco/Twitch-Drops-Bot#227]
**Describe the bug**
Seems like the bot cant claim drops and even got an error in the middle before doing it.

**Logs**
```cmd
[2022-10-11 12:38:59] [error] Error watching stream
[2022-10-11 12:38:59] [info] Watched stream for 15 minutes
[2022-10-11 12:38:59] [error] Error processing campaign
[2022-10-11 12:38:59] [info] Processing campaign: Albion Online Into the Fray Week 18 Campaign
[2022-10-11 12:38:59] [warn] Twitch account not linked for this campaign!
[2022-10-11 12:38:59] [error] Error processing campaign
[2022-10-11 12:38:59] [info] Processing campaign: The Cycle: Frontier Drops Day 11th Oct
[2022-10-11 12:38:59] [warn] Twitch account not linked for this campaign!
[2022-10-11 12:39:00] [info] Found 30 good streams
[2022-10-11 12:39:00] [info] Watching stream: https://www.twitch.tv/chap
[2022-10-11 12:39:30] [error] Uncaught exception: TimeoutError: Timeout exceeded while waiting for event
    at Timeout.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/util.js:168:28)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
(node:1) UnhandledPromiseRejectionWarning: TimeoutError: Timeout exceeded while waiting for event
at Timeout.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/util.js:168:28)
at listOnTimeout (node:internal/timers:564:17)
at process.processTimers (node:internal/timers:507:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[2022-10-11 12:53:40] [error] Failed to claim drop reward
[2022-10-11 12:53:48] [info] Higher priority campaign found: Albion Online Into the Fray Week 18 Campaign id: 7c11507d-688b-4c1c-b0ca-e988c48955a8
[2022-10-11 13:08:40] [error] Failed to claim drop reward
[2022-10-11 13:08:48] [info] Higher priority campaign found: Albion Online Into the Fray Week 18 Campaign id: 7c11507d-688b-4c1c-b0ca-e988c48955a8
[2022-10-11 13:23:40] [error] Failed to claim drop reward
[2022-10-11 13:23:48] [info] Higher priority campaign found: Albion Online Into the Fray Week 18 Campaign id: 7c11507d-688b-4c1c-b0ca-e988c48955a8
[2022-10-11 13:38:40] [error] Failed to claim drop reward
[2022-10-11 13:38:48] [info] Higher priority campaign found: Albion Online Into the Fray Week 18 Campaign id: 7c11507d-688b-4c1c-b0ca-e988c48955a8
[2022-10-11 13:53:41] [error] Failed to claim drop reward
[2022-10-11 13:53:49] [info] Higher priority campaign found: Albion Online Into the Fray Week 18 Campaign id: 7c11507d-688b-4c1c-b0ca-e988c48955a8
[2022-10-11 14:08:41] [error] Failed to claim drop reward
[2022-10-11 14:08:49] [info] Higher priority campaign found: Albion Online Into the Fray Week 18 Campaign id: 7c11507d-688b-4c1c-b0ca-e988c48955a8
[2022-10-11 14:23:41] [error] Failed to claim drop reward
[2022-10-11 14:23:49] [info] Higher priority campaign found: Albion Online Into the Fray Week 18 Campaign id: 7c11507d-688b-4c1c-b0ca-e988c48955a8
```

**Comment by jaredkotoff** [comment]
Think this is a duplicate of https://github.com/TychoTheTaco/Twitch-Drops-Bot/issues/212
