### ISSUE TITLE
Error: Cannot find module 'winston'

### ISSUE THREAD

**Issue by m7zr** [TychoTheTaco/Twitch-Drops-Bot#24]
Error: Cannot find module 'winston'
how i can fix this please

**Comment by TychoTheTaco** [comment]
You can run `npm install .` to install all the dependencies for this bot, including winston.

**Comment by m7zr** [comment]
i did but still asking for module 'winston'

**Comment by m7zr** [comment]
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[##################] | reify:typescript: timing reifyNode:node_modules/puppeteer Completed in 2400ms

**Comment by TychoTheTaco** [comment]
I'm not sure about those errors. Maybe you are using an older version of Node.js? This bot requires Node.js 14+.

**Comment by m7zr** [comment]
i have node.js v16.130.

**Comment by m7zr** [comment]
PS D:\Twitch-Drops-Bot-master> npm run start

> twitch_drops_bot@1.0.0 start
> node dist/index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'winston'
Require stack:
- D:\Twitch-Drops-Bot-master\dist\logger.js
- D:\Twitch-Drops-Bot-master\dist\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Twitch-Drops-Bot-master\dist\logger.js:4:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Twitch-Drops-Bot-master\\dist\\logger.js',
    'D:\\Twitch-Drops-Bot-master\\dist\\index.js'
  ]
}
PS D:\Twitch-Drops-Bot-master>

**Comment by m7zr** [comment]
help pls :(

**Comment by m7zr** [comment]
i use windows power shell is that ok ?

**Comment by TychoTheTaco** [comment]
Sorry I'm not sure how to help. This seems like an issue with your setup/environment. I have tried using power shell and it works for me.

**Comment by m7zr** [comment]
do i need docker or puppeteer for its cuz idk how to use it , if you can do a youtube video for how to use yout bot please.

**Comment by TychoTheTaco** [comment]
You do not need to use docker but you do need to have puppeteer installed. I don't have time to make a YouTube video. The usage instructions are at the top of the readme.

**Comment by m7zr** [comment]
i fixed everything but now i have this :(
PS D:\bots\Twitch-Drops-Bot-master> node dist/index.js
[2021-12-27 08:52:22] [info] Loading config file: config.json
[2021-12-27 08:52:22] [error] Failed to read config file!
[2021-12-27 08:52:22] [error] Unexpected token c in JSON at position 20 SyntaxError: Unexpected token c in JSON at position 20
    at JSON.parse (<anonymous>)
    at ConfigurationParser.parse (D:\bots\Twitch-Drops-Bot-master\dist\configuration_parser.js:48:31)
    at Object.<anonymous> (D:\bots\Twitch-Drops-Bot-master\dist\index.js:78:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
PS D:\bots\Twitch-Drops-Bot-master>
