### ISSUE TITLE
[Bug] Twitch-Drops-Bot doesn't work

### ISSUE THREAD

**Issue by BulldozerPete** [TychoTheTaco/Twitch-Drops-Bot#240]
**Describe the bug**
Twitch-Drops-Bot doesn't work

**Screenshots**

**Logs**
[2022-10-21 05:11:20] [error] TypeError: config.notifications.telegram is not iterable
    at file:///app/dist/index.js:613:53
    at Generator.next (<anonymous>)
    at file:///app/dist/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///app/dist/index.js:3:12)
    at setUpNotifiers (file:///app/dist/index.js:589:12)
    at file:///app/dist/index.js:553:15
    at Generator.next (<anonymous>)
    at fulfilled (file:///app/dist/index.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by JourneyOver** [comment]
This release requires a different format of the config when using notifications! See [the docs](https://github.com/TychoTheTaco/Twitch-Drops-Bot/blob/dev/docs/notifications.md) for the new format..

You need to update your config file to the new format.

**Comment by TychoTheTaco** [comment]
Fixed in latest release.
