### ISSUE TITLE
[error] Failed to read config file!

### ISSUE THREAD

**Issue by m7zr** [TychoTheTaco/Twitch-Drops-Bot#26]
PS D:\bots\Twitch-Drops-Bot-master> node dist/index.js
[2021-12-27 08:52:22] [info] Loading config file: config.json
[2021-12-27 08:52:22] [error] Failed to read config file!
[2021-12-27 08:52:22] [error] Unexpected token c in JSON at position 20 SyntaxError: Unexpected token c in JSON at position 20
at JSON.parse ()
at ConfigurationParser.parse (D:\bots\Twitch-Drops-Bot-master\dist\configuration_parser.js:48:31)
at Object. (D:\bots\Twitch-Drops-Bot-master\dist\index.js:78:34)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:17:47
PS D:\bots\Twitch-Drops-Bot-master>

**Comment by TychoTheTaco** [comment]
Please post your config file. Make sure to remove your password (if you added it) before uploading it!

**Comment by m7zr** [comment]
{"browser":"C:\Program Files\Google\Chrome\Application\chrome.exe","games":[1063730],"headless":true,"headless_login":false,"interval":15,"browser_args":[],"watch_unlisted_games":false,"show_account_not_linked_warning":true}

**Comment by Jorgen1040** [comment]
@m7zr you need to put quotes (") around each game ID for games.

So in your case it should be `"games":["1063730"]`

**Comment by m7zr** [comment]
{
    "browser": "D:\bots\chrome-win\\Application\\chrome.exe",
    "games": ["30921", "511224", "488552"],
    "headless": true,
    "headless_login": false,
    "interval": 15,
    "browser_args": []
}

did it and still the same it sayes now
PS D:\bots\Twitch-Drops-Bot-master> node dist/index.js
[2021-12-27 08:52:22] [info] Loading config file: config.json
[2021-12-27 08:52:22] [error] Failed to read config file!
[2021-12-27 08:52:22] [error] Unexpected token c in JSON at position 20 SyntaxError: Unexpected token c in JSON at position 20
at JSON.parse ()
at ConfigurationParser.parse (D:\bots\Twitch-Drops-Bot-master\dist\configuration_parser.js:48:31)
at Object. (D:\bots\Twitch-Drops-Bot-master\dist\index.js:78:34)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:17:47
PS D:\bots\Twitch-Drops-Bot-master>

**Comment by Jorgen1040** [comment]
Oh, you need to use double backslashes when you specify browser (to escape the escape character).
So yours should be:
`"browser": "D:\\bots\\chrome-win\\Application\\chrome.exe"`

**Comment by m7zr** [comment]
when i did that it sayes now

PS D:\bots\Twitch-Drops-Bot-master> npm run start

> twitch_drops_bot@1.0.0 start
> node dist/index.js

[2021-12-29 01:27:10] [info] Loading config file: config.json
[2021-12-29 01:27:10] [error] Failed to launch the browser process! spawn D:\bots\chrome-win\Application\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 Error: Failed to launch the browser process! spawn D:\bots\chrome-win\Application\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (D:\bots\Twitch-Drops-Bot-master\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:229:20)
    at ChildProcess.<anonymous> (D:\bots\Twitch-Drops-Bot-master\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:221:85)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
PS D:\bots\Twitch-Drops-Bot-master>

**Comment by m7zr** [comment]
last update for now 

PS D:\bots\Twitch-Drops-Bot-master> npm run start

> twitch_drops_bot@1.0.0 start
> node dist/index.js

[2021-12-29 01:53:39] [info] Loading config file: config.json
[2021-12-29 01:53:39] [error] Failed to read config file!
[2021-12-29 01:53:39] [error] Unexpected token : in JSON at position 27 SyntaxError: Unexpected token : in JSON at position 27
    at JSON.parse (<anonymous>)
    at ConfigurationParser.parse (D:\bots\Twitch-Drops-Bot-master\dist\configuration_parser.js:48:31)
    at Object.<anonymous> (D:\bots\Twitch-Drops-Bot-master\dist\index.js:78:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
PS D:\bots\Twitch-Drops-Bot-master>

**Comment by m7zr** [comment]
@Jorgen1040 can you help please

**Comment by Jorgen1040** [comment]
How does your config file look now? If you look at the error message, it's complaining of an unexpected `:` at position 27, but that doesn't seem to match the config you sent in previous messages.

**Comment by Jorgen1040** [comment]
@m7zr if it got fixed please close this issue :)
