### ISSUE TITLE
Cannot run on EC2 server

### ISSUE THREAD

**Issue by LunasWH** [TychoTheTaco/Twitch-Drops-Bot#270]
I am trying to run the program on a Ubuntu EC2 server, and I have set it up, google-chrome is also installed, but when I am getting an error Failed to launch browser process, and when i try to launch chrome i get another error sayin that i cannot run it without sandbox

The errors in question:

[2022-12-18 16:58:20] [error] Error: Failed to launch the browser process! spawn /usr/bin/google-chrome /usr/share/man/man1/google-chrome.1.gz ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/ubuntu/botviewer/Twitch-Drops-Bot/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at ChildProcess.<anonymous> (/home/ubuntu/botviewer/Twitch-Drops-Bot/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:293:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

And

google-chrome --no-sandbox
[71752:71752:1218/170205.539633:ERROR:ozone_platform_x11.cc(238)] Missing X server or $DISPLAY
[71752:71752:1218/170205.539902:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
[1218/170205.564135:ERROR:nacl_helper_linux.cc(355)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly

**Comment by agret** [comment]
You'll need to be running it from the desktop, it won't work in an SSH terminal.

https://ubuntu.com/tutorials/ubuntu-desktop-aws

This guide suggests opening the VNC server to the world by forwarding the port through the firewall, I would use SSH port tunneling instead of doing that.
