### ISSUE TITLE
SyntaxError: Bad escaped character in JSON at position 21     at JSON.parse [Bug]

### ISSUE THREAD

**Issue by SwiftExplorer567** [TychoTheTaco/Twitch-Drops-Bot#273]
I cannot run the code due to the error:

```
[2022-12-27 18:46:14] [error] Failed to read config file!
[2022-12-27 18:46:14] [error] SyntaxError: Bad escaped character in JSON at position 21
    at JSON.parse (<anonymous>)
    at ConfigurationParser.parse (file:///C:/Users/Hasan/OneDrive/Masa%C3%BCst%C3%BC/Twitch-Drops-Bot-dev/dist/configuration_parser.js:57:31)
    at file:///C:/Users/Hasan/OneDrive/Masa%C3%BCst%C3%BC/Twitch-Drops-Bot-dev/dist/index.js:351:42
    at Generator.next (<anonymous>)
    at file:///C:/Users/Hasan/OneDrive/Masa%C3%BCst%C3%BC/Twitch-Drops-Bot-dev/dist/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///C:/Users/Hasan/OneDrive/Masa%C3%BCst%C3%BC/Twitch-Drops-Bot-dev/dist/index.js:3:12)
    at main (file:///C:/Users/Hasan/OneDrive/Masa%C3%BCst%C3%BC/Twitch-Drops-Bot-dev/dist/index.js:348:12)
    at file:///C:/Users/Hasan/OneDrive/Masa%C3%BCst%C3%BC/Twitch-Drops-Bot-dev/dist/index.js:706:5
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Changed the location and the error:

```
[2022-12-27 18:51:01] [error] Failed to read config file!
[2022-12-27 18:51:01] [error] SyntaxError: Bad escaped character in JSON at position 21
    at JSON.parse (<anonymous>)
    at ConfigurationParser.parse (file:///C:/Twitch-Drops-Bot-dev/dist/configuration_parser.js:57:31)
    at file:///C:/Twitch-Drops-Bot-dev/dist/index.js:351:42
    at Generator.next (<anonymous>)
    at file:///C:/Twitch-Drops-Bot-dev/dist/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///C:/Twitch-Drops-Bot-dev/dist/index.js:3:12)
    at main (file:///C:/Twitch-Drops-Bot-dev/dist/index.js:348:12)
    at file:///C:/Twitch-Drops-Bot-dev/dist/index.js:706:5
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by jaredcat** [comment]
Your config file is messed up. 
Paste it into there and see if you can fix it: https://jsonformatter.curiousconcept.com
