### ISSUE TITLE
Bot no longer working, error at launch

### ISSUE THREAD

**Issue by dmitriyvostrikov** [TychoTheTaco/Twitch-Drops-Bot#274]
**Describe the bug**
Bot no longer works, getting an error at launch. 

Using this docker-compose file(in case I missed something?):
```
version: '3'

services:
  twitchdrops:
    image: ghcr.io/tychothetaco/twitch-drops-bot:latest-release
    container_name: twitchdrops
    restart: unless-stopped
    volumes:
      - ./data:/app/data
````

**Screenshots**
N/A

**Logs**
```
[2022-12-30 12:53:25] [info] Loading config file: config.json  
[2022-12-30 12:53:25] [warn] Overriding browser option because we are inside a docker container!  
[2022-12-30 12:53:25] [warn] Adding browser option: --no-sandbox because we are inside a docker container!  
[2022-12-30 12:53:25] [warn] No username specified! Using existing cookies: cookies-***.json  
[2022-12-30 12:53:25] [info] Restoring cookies from last session.  
[2022-12-30 12:53:25] [error] AxiosError: Request failed with status code 401  
    at settle (file:///app/node_modules/axios/lib/core/settle.js:19:12)  
    at IncomingMessage.handleStreamEnd (file:///app/node_modules/axios/lib/adapters/http.js:495:11)  
    at IncomingMessage.emit (node:events:525:35)  
    at endReadableNT (node:internal/streams/readable:1359:12)  
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)  
````

**Comment by M-archand** [comment]
I'm getting the exact same error on startup.

**Comment by thierrybla** [comment]
> I'm getting the exact same error on startup.

Me too
