### ISSUE TITLE
[Bug] Bot gets stuck on extra verification at the start

### ISSUE THREAD

**Issue by Nubidubi23** [TychoTheTaco/Twitch-Drops-Bot#326]
![image](https://github.com/TychoTheTaco/Twitch-Drops-Bot/assets/48162191/0cac76b6-9da5-4463-a106-423b0a324dcb)

Also text form if it helps:

```
[2023-08-06 07:55:00] [warn] Overriding browser option because we are inside a docker container!
[2023-08-06 07:55:00] [warn] Adding browser option: --no-sandbox because we are inside a docker container!
[2023-08-06 07:55:02] [info] Logging in...
[2023-08-06 07:55:05] [info] Checking for email verification...
[2023-08-06 07:55:35] [error] TimeoutError: Waiting for selector `.//*[contains(text(), "please enter the 6-digit code we sent")]` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64:32)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[2023-08-06 07:55:35] [info] Checking for 2FA verification...
[2023-08-06 07:56:05] [error] TimeoutError: Waiting for selector `.//*[contains(text(), "Enter the code found in your authenticator app")]` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64:32)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[2023-08-06 07:56:05] [info] No extra verification found!
[2023-08-06 07:56:05] [info] Waiting for cookies to be created...
[2023-08-06 07:56:08] [info] Waiting for cookies to be created...
[2023-08-06 07:56:11] [info] Waiting for cookies to be created...
[2023-08-06 07:56:14] [info] Waiting for cookies to be created...
[2023-08-06 07:56:17] [info] Waiting for cookies to be created...
[2023-08-06 07:56:20] [info] Waiting for cookies to be created...
[2023-08-06 07:56:23] [info] Waiting for cookies to be created...
[2023-08-06 07:56:26] [info] Waiting for cookies to be created...
[2023-08-06 07:56:29] [info] Waiting for cookies to be created...
[2023-08-06 07:56:32] [info] Waiting for cookies to be created...
[2023-08-06 07:56:35] [error] Error: Timed out while waiting for cookies to be created!
    at LoginPage.<anonymous> (file:///app/dist/pages/login.js:62:31)
    at Generator.next (<anonymous>)
    at fulfilled (file:///app/dist/pages/login.js:4:58)

```

**Comment by Nubidubi23** [comment]
Nevermind, i looked through older issues and @BlackNLl16 saved it for me. Apparently the regular login method doesn't work so i had to copy my login cookies
