### ISSUE TITLE
 TimeoutError

### ISSUE THREAD

**Issue by philip47** [TychoTheTaco/Twitch-Drops-Bot#328]
It's very difficult to configure this bot. I can't find any information on what to do anywhere.  Maybe somebody can help me?

2023-09-24 19:29:43 [2023-09-24 22:29:43] [info] Loading config file: config.json
2023-09-24 19:29:43 [2023-09-24 22:29:43] [warn] Overriding browser option because we are inside a docker container!
2023-09-24 19:29:43 [2023-09-24 22:29:43] [warn] Overriding headless_login option because we are inside a docker container!
2023-09-24 19:29:43 [2023-09-24 22:29:43] [warn] Adding browser option: --no-sandbox because we are inside a docker container!
2023-09-24 19:29:43 [2023-09-24 22:29:43] [info] Logging in...
2023-09-24 19:29:47 [2023-09-24 22:29:47] [info] Checking for email verification...
2023-09-24 19:30:17 [2023-09-24 22:30:17] [error] TimeoutError: Waiting for selector `.//*[contains(text(), "please enter the 6-digit code we sent")]` failed: Waiting failed: 30000ms exceeded

**Comment by YannD-Deltagon** [comment]
same here, no solution

edit : Docker on Windows Docker Desktop
And config in a Volume
All configurat

**Comment by YannD-Deltagon** [comment]
I have 2FA

> [2023-10-31 09:49:41] [warn] Overriding browser option because we are inside a docker container!
> [2023-10-31 09:49:41] [warn] Overriding headless option because we are inside a docker container!
> [2023-10-31 09:49:41] [warn] Overriding headless_login option because we are inside a docker container!
> [2023-10-31 09:49:41] [warn] Adding browser option: --no-sandbox because we are inside a docker container!
> [2023-10-31 09:49:42] [info] Logging in...
> [2023-10-31 09:49:45] [info] Checking for email verification...
> [2023-10-31 09:50:15] [error] TimeoutError: Waiting for selector `.//*[contains(text(), "please enter the 6-digit code we sent")]` failed: Waiting failed: 30000ms exceeded
>     at Timeout.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:63:32)
>     at listOnTimeout (node:internal/timers:573:17)
>     at process.processTimers (node:internal/timers:514:7)
> [2023-10-31 09:50:15] [info] Checking for 2FA verification...
> [2023-10-31 09:50:45] [error] TimeoutError: Waiting for selector `.//*[contains(text(), "Enter the code found in your authenticator app")]` failed: Waiting failed: 30000ms exceeded
>     at Timeout.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:63:32)
>     at listOnTimeout (node:internal/timers:573:17)
>     at process.processTimers (node:internal/timers:514:7)
> [2023-10-31 09:50:45] [info] No extra verification found!
> [2023-10-31 09:50:45] [info] Waiting for cookies to be created...
> [2023-10-31 09:50:48] [info] Waiting for cookies to be created...
> [2023-10-31 09:50:51] [info] Waiting for cookies to be created...
> [2023-10-31 09:50:54] [info] Waiting for cookies to be created...
> [2023-10-31 09:50:57] [info] Waiting for cookies to be created...
> [2023-10-31 09:51:00] [info] Waiting for cookies to be created...
> [2023-10-31 09:51:03] [info] Waiting for cookies to be created...
> [2023-10-31 09:51:06] [info] Waiting for cookies to be created...
> [2023-10-31 09:51:09] [info] Waiting for cookies to be created...
> [2023-10-31 09:51:12] [info] Waiting for cookies to be created...
> [2023-10-31 09:51:15] [error] Error: Timed out while waiting for cookies to be created!
>     at LoginPage.<anonymous> (file:///app/dist/pages/login.js:62:31)
>     at Generator.next (<anonymous>)
>     at fulfilled (file:///app/dist/pages/login.js:4:58)

**Comment by tranqu1lizer** [comment]
same issue
![image](https://github.com/TychoTheTaco/Twitch-Drops-Bot/assets/108815933/7d6b296f-94a7-4f30-bced-2de783ed213c)

**Comment by YannD-Deltagon** [comment]
I use the Windows .exe on the pre-realese

**Comment by tranqu1lizer** [comment]
twitch detects puppeteer on login page so need to llogin using cookies
