### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by nipser** [TychoTheTaco/Twitch-Drops-Bot#41]
Hey,

I am having an issue with logging in. After the 2FA, my docker process crashed printing the following:

`[2022-01-22 20:20:37] [error] Failed to login. There was probably an extra verification step that this app didn't check for. A screenshot of the page will be saved to failed-login-screenshot-1642882837764.png and the page content will be saved to failed-login-html-1642882837764.html. Please create an issue on GitHub with both of these files.
[2022-01-22 20:20:57] [error] Navigation timeout of 30000 ms exceeded TimeoutError: Navigation timeout of 30000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.waitForFrameNavigation (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:128:23)
    at async Frame.waitForNavigation (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:441:16)
    at async Page.waitForNavigation (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1218:16)`

According to the screenshot, I'm logged in perfectly fine. Maybe the bot is having trouble with the cookie popup?

BR nipser

![failed-login-screenshot-1642882837764](https://user-images.githubusercontent.com/11896495/150655183-c03169d8-a655-459c-bb4c-2c830851ef01.png)

[failed-login-html-1642882837764.txt](https://github.com/TychoTheTaco/Twitch-Drops-Bot/files/7919276/failed-login-html-1642882837764.txt)

**Comment by nipser** [comment]
Increasing the timeout seemed to have done the trick...
