### ISSUE TITLE
Get an error on first time setup.

### ISSUE THREAD

**Issue by phrostb** [TychoTheTaco/Twitch-Drops-Bot#46]
I followed all the instructions but I get this error.. I checked the Puppeteer troubleshooting but it's a bit confusing. I'm not a coder. Can you help me out please? 

`D:\Download\Twitch-Drops-Bot-master>node dist/index.js
[2022-02-05 20:48:25] [info] Loading config file: config.json
[2022-02-05 20:48:25] [error] Failed to launch the browser process! spawn C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 Error: Failed to launch the browser process! spawn C:\Program Files (x86)\Google\Chrome\Application\chrome.exe ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (D:\Download\Twitch-Drops-Bot-master\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:197:20)
    at ChildProcess.<anonymous> (D:\Download\Twitch-Drops-Bot-master\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:189:85)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
`

**Comment by phrostb** [comment]
Ok I realized it's because I have 64bit chrome and not 32bit. So I copied chrome.exe into C:\Program Files (x86)\Google\Chrome\Application and have a new error `[2022-02-06 05:55:43] [info] Loading config file: config.json
[2022-02-06 05:55:43] [error] spawn UNKNOWN Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at BrowserRunner.start (D:\Download\twitch\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:80:34)
    at ChromeLauncher.launch (D:\Download\twitch\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:94:16)
    at PuppeteerNode.launch (D:\Download\twitch\node_modules\puppeteer\lib\cjs\puppeteer\node\Puppeteer.js:125:31)
    at PuppeteerExtra.launch (D:\Download\twitch\node_modules\puppeteer-extra\dist\index.cjs.js:129:41)`

**Comment by phrostb** [comment]
Ok I fixed it by removing the x86 from my Chrome path, but now I don't see Rocket League in the campaign list., and I know it works on my account, everything is linked. I'll keep researching.

**Comment by phrostb** [comment]
I see now that by default it only shows games that aren't linked in the main window, I figured it out! Great software, thanks for everything!
