### ISSUE TITLE
Failed to login with correct credential

### ISSUE THREAD

**Issue by Ryan-He** [TychoTheTaco/Twitch-Drops-Bot#52]
It always failed to login even I did receive email notification of success login from twitch.
I tried remove F2A but still failed.
########################################################
[2022-02-17 06:11:25] [info] Loading config file: config.json
[2022-02-17 06:11:25] [debug] git commit hash: ed3ccb9a6ff1f6454f788bd678e9561b314c820d
[2022-02-17 06:11:25] [debug] Using config: {
    "browser": "chromium",
    "games": [
        "511224",
        "460630",
        "491931"
    ],
    "headless": true,
    "headless_login": true,
    "username": "lucky_ro",
    "password": "present",
    "interval": 15,
    "load_timeout_secs": 120,
    "failed_stream_retry": 3,
    "failed_stream_timeout": 30,
    "browser_args": [
        "--no-sandbox",
        "--mute-audio",
        "--disable-background-timer-throttling",
        "--disable-backgrounding-occluded-windows",
        "--disable-renderer-backgrounding",
        "--window-size=1920,1080"
    ],
    "watch_unlisted_games": true,
    "hide_video": true,
    "show_account_not_linked_warning": true,
    "ignored_games": [],
    "attempt_impossible_campaigns": true,
    "watch_streams_when_no_drop_campaigns_active": false,
    "broadcasters": []
}
[2022-02-17 06:11:30] [info] Logging in...
[2022-02-17 06:11:44] [info] Checking for email verification...
[2022-02-17 06:11:50] [info] Email verification found.
[2022-02-17 06:12:47] [error] Failed to login. There was probably an extra verification step that this app didn't check for. A screenshot of the page will be saved to failed-login-screenshot-1645078367573.png and the page content will be saved to failed-login-html-1645078367573.html. Please create an issue on GitHub with both of these files.
[2022-02-17 06:13:14] [error] Navigation timeout of 30000 ms exceeded TimeoutError: Navigation timeout of 30000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.waitForFrameNavigation (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:128:23)
    at async Frame.waitForNavigation (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:441:16)
    at async Page.waitForNavigation (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1218:16
########################################################
[2022-02-17 05:59:15] [info] Loading config file: config.json
[2022-02-17 05:59:15] [debug] git commit hash: ed3ccb9a6ff1f6454f788bd678e9561b314c820d
[2022-02-17 05:59:15] [debug] Using config: {
    "browser": "chromium",
    "games": [
        "511224",
        "460630",
        "491931"
    ],
    "headless": true,
    "headless_login": true,
    "username": "lucky_ro",
    "password": "present",
    "interval": 15,
    "load_timeout_secs": 120,
    "failed_stream_retry": 3,
    "failed_stream_timeout": 30,
    "browser_args": [
        "--no-sandbox",
        "--mute-audio",
        "--disable-background-timer-throttling",
        "--disable-backgrounding-occluded-windows",
        "--disable-renderer-backgrounding",
        "--window-size=1920,1080"
    ],
    "watch_unlisted_games": true,
    "hide_video": true,
    "show_account_not_linked_warning": true,
    "ignored_games": [],
    "attempt_impossible_campaigns": true,
    "watch_streams_when_no_drop_campaigns_active": false,
    "broadcasters": []
}
[2022-02-17 05:59:19] [info] Logging in...
[2022-02-17 05:59:29] [info] Checking for email verification...
[2022-02-17 05:59:59] [info] Email verification not found.
[2022-02-17 05:59:59] [info] Checking for 2FA verification...
[2022-02-17 05:59:59] [info] 2FA verification found.
[2022-02-17 06:00:53] [error] Failed to login. There was probably an extra verification step that this app didn't check for. A screenshot of the page will be saved to failed-login-screenshot-1645077653055.png and the page content will be saved to failed-login-html-1645077653055.html. Please create an issue on GitHub with both of these files.
[2022-02-17 06:01:14] [error] Navigation timeout of 30000 ms exceeded TimeoutError: Navigation timeout of 30000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.waitForFrameNavigation (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:128:23)
    at async Frame.waitForNavigation (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:441:16)
    at async Page.waitForNavigation (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1218:16)
#######################################################
![failed-login-screenshot-1645077653055](https://user-images.githubusercontent.com/15955171/154417125-d81cb746-5ef3-4249-8638-3a9168ff7d45.png)
)

**Comment by TychoTheTaco** [comment]
It looks like the page didn't load on time, which is why we get a `NavigationTimeout`. From your log output, I did notice a bug (you have the timeout set to 120 seconds, but the `TimeoutError` was thrown after only 30 seconds), so I'll have to fix that. I will see if there is a better way to detect if the login was successful other than waiting for the page to load.
