### ISSUE TITLE
[Bug] Breaks at "Checking for email verification..." (WSL2)

### ISSUE THREAD

**Issue by skupfer** [TychoTheTaco/Twitch-Drops-Bot#59]
**Describe the bug**
Loaded the docker images, setup the config with a username and password, ran the container as per linux

**Logs**
```
docker run -v ${PWD}:/app/data -i -t --sig-proxy=false ghcr.io/tychothetaco/twitch-drops-bot
[2022-03-20 20:21:35] [info] Loading config file: config.json
[2022-03-20 20:21:36] [info] Logging in...
[2022-03-20 20:21:38] [info] Checking for email verification...
[2022-03-20 20:22:08] [error] TypeError: Right-hand side of 'instanceof' is not an object
    at LoginPage.<anonymous> (/app/dist/pages/login.js:119:35)
    at Generator.throw (<anonymous>)
    at rejected (/app/dist/pages/login.js:6:65)+
```

Is this WSL-related or is there something missing. I am at commit 66317241efce84ab7b1e7154962df91634fbead4

**Comment by TychoTheTaco** [comment]
Fixed this in the latest commit.
